# Generated by Django 4.2.11 on 2025-01-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tagmodel_product_short_description_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'tags'},
        ),
    ]
