# Generated by Django 4.2.11 on 2025-01-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_tags_producttagsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttagsmodel',
            old_name='characteristic',
            new_name='tag',
        ),
    ]
