# Generated by Django 4.2.11 on 2025-01-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_characteristic_producttagsmodel_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
