# Generated by Django 4.2.11 on 2025-01-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_reviewmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.DeleteModel(
            name='ProductTagsModel',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
