# Generated by Django 4.2.11 on 2025-01-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseller',
            name='delivery_type',
            field=models.CharField(choices=[('STANDARD', 'Обычная доставка'), ('EXPRESS', 'Быстрая доставка'), ('FREE', 'Бесплатная доставка')], default='STANDARD', max_length=10, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='productseller',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'Онлайн картой'), ('CASH', 'Наличными')], default='CARD', max_length=50, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='productseller',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товара'),
        ),
    ]
