# Generated by Django 4.2.11 on 2024-12-12 19:47

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_avatar_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[profiles.models.validate_image_size]),
        ),
    ]
