# Generated by Django 4.2.11 on 2025-01-21 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='card_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='card number'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('not success', 'Not success')], default='not success', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total cost of the order'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('express', 'Express')], default='usually', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pay',
            field=models.CharField(choices=[('online', 'Online cart'), ('someone', "Online from a random stranger's account.")], default='online', max_length=100),
        ),
    ]
