# Generated by Django 4.2.11 on 2025-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_card_number_ordermodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('ordinary', 'Ordinary'), ('express', 'Express')], default='usually', max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='The Сost of the delivery')),
                ('total_price_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total price for order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deliverypricemodel',
            constraint=models.CheckConstraint(check=models.Q(('delivery__in', ['ordinary', 'express'])), name='delivery_type_check'),
        ),
    ]
