# Generated by Django 4.2.11 on 2025-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliverypricemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='error_message',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Payment error message'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='id for payment service'),
        ),
    ]
