# Generated by Django 4.2.11 on 2025-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermodel_error_message_ordermodel_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='id for payment service'),
        ),
    ]
